# Generated by Django 2.0.1 on 2018-05-13 15:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='submission_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='submission',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='round',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
