# Generated by Django 2.0.1 on 2018-05-13 21:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20180513_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='started',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submitted',
            field=models.DateTimeField(),
        ),
    ]
