# Generated by Django 2.0.1 on 2018-05-13 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20180513_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='coaches',
        ),
        migrations.RemoveField(
            model_name='team',
            name='head_coaches',
        ),
        migrations.RemoveField(
            model_name='team',
            name='members',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
