# Generated by Django 2.0.1 on 2018-05-14 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_round_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='solution',
            new_name='correct_answer',
        ),
    ]
