# Generated by Django 2.0.1 on 2018-05-14 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20180514_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
