# Generated by Django 2.0.1 on 2018-05-15 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_round_pdf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='round',
            old_name='pdf',
            new_name='file',
        ),
    ]
