# Generated by Django 2.0.1 on 2018-05-15 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20180514_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round',
            name='image',
        ),
    ]
