# Generated by Django 2.0.1 on 2018-05-15 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_remove_round_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='points',
            field=models.TextField(default=''),
        ),
    ]
