# Generated by Django 2.0.1 on 2018-05-17 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20180514_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='contest_index',
            field=models.CharField(choices=[('ONE', 'One'), ('TWO', 'Two'), ('THREE', 'Three'), ('FOUR', 'Four'), ('FIVE', 'Five'), ('SIX', 'Six')], default='ONE', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='round',
            name='league',
            field=models.CharField(choices=[('GBML', 'Greater Boston Mathematics League'), ('MML', 'Massachusetts Mathematics League'), ('NEAML', 'New England Association of Math Leagues')], default='MML', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='round',
            name='month',
            field=models.CharField(choices=[('JANUARY', 'January'), ('FEBRUARY', 'February'), ('MARCH', 'March'), ('APRIL', 'April'), ('MAY', 'May'), ('JUNE', 'June'), ('JULY', 'July'), ('AUGUST', 'August'), ('SEPTEMBER', 'September'), ('OCTOBER', 'October'), ('NOVEMBER', 'November'), ('DECEMBER', 'December')], default='OCTOBER', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='round',
            name='round_index',
            field=models.CharField(choices=[('ONE', 'One'), ('TWO', 'Two'), ('THREE', 'Three'), ('FOUR', 'Four'), ('FIVE', 'Five'), ('SIX', 'Six')], default='ONE', max_length=16),
            preserve_default=False,
        ),
    ]
