# Generated by Django 2.0.1 on 2018-05-17 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20180516_2030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round',
            name='month',
        ),
    ]
