# Generated by Django 2.0.1 on 2018-05-17 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_round_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='submission_image',
        ),
        migrations.AddField(
            model_name='submission',
            name='submission_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
