# Generated by Django 2.0.1 on 2018-05-17 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20180516_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='round_index',
            field=models.CharField(choices=[('ONE', 'One'), ('TWO', 'Two'), ('THREE', 'Three'), ('FOUR', 'Four'), ('FIVE', 'Five'), ('SIX', 'Six'), ('SEVEN', 'Seven')], max_length=16),
        ),
    ]
