# Generated by Django 2.0.1 on 2018-05-17 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20180517_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='question',
            field=models.TextField(default=''),
        ),
    ]
