# Generated by Django 2.0.1 on 2018-05-17 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20180517_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round',
            name='problems',
        ),
        migrations.AddField(
            model_name='round',
            name='correct_answers',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Problem',
        ),
    ]
