# Generated by Django 2.0.1 on 2018-05-18 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20180517_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league', models.CharField(choices=[('GBML', 'Greater Boston Mathematics League'), ('MML', 'Massachusetts Mathematics League'), ('NEAML', 'New England Association of Math Leagues')], max_length=64)),
                ('contest_index', models.CharField(choices=[('ONE', 'One'), ('TWO', 'Two'), ('THREE', 'Three'), ('FOUR', 'Four'), ('FIVE', 'Five'), ('SIX', 'Six')], max_length=16)),
                ('year', models.IntegerField(default=2018)),
            ],
        ),
    ]
