# Generated by Django 2.0.1 on 2018-05-18 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_meet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meet',
            old_name='year',
            new_name='start_year',
        ),
    ]
