# Generated by Django 2.0.1 on 2018-05-18 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_auto_20180518_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round',
            name='contest_index',
        ),
        migrations.RemoveField(
            model_name='round',
            name='id',
        ),
        migrations.RemoveField(
            model_name='round',
            name='league',
        ),
        migrations.RemoveField(
            model_name='round',
            name='year',
        ),
        migrations.AddField(
            model_name='round',
            name='meet_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.Meet'),
            preserve_default=False,
        ),
    ]
