# Generated by Django 2.0.1 on 2018-05-18 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_auto_20180518_1544'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Meet',
        ),
        migrations.RemoveField(
            model_name='round',
            name='meet_ptr',
        ),
        migrations.AddField(
            model_name='round',
            name='contest_index',
            field=models.CharField(choices=[('ONE', 'One'), ('TWO', 'Two'), ('THREE', 'Three'), ('FOUR', 'Four'), ('FIVE', 'Five'), ('SIX', 'Six')], default=None, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='round',
            name='id',
            field=models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='round',
            name='league',
            field=models.CharField(choices=[('GBML', 'Greater Boston Mathematics League'), ('MML', 'Massachusetts Mathematics League'), ('NEAML', 'New England Association of Math Leagues')], default=None, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='round',
            name='start_year',
            field=models.IntegerField(default=2018),
        ),
    ]
