# Generated by Django 2.0.1 on 2018-05-18 20:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0033_auto_20180518_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league', models.CharField(choices=[('GBML', 'Greater Boston Mathematics League'), ('MML', 'Massachusetts Mathematics League'), ('NEAML', 'New England Association of Math Leagues')], max_length=64)),
                ('contest_index', models.CharField(choices=[('ONE', 'One'), ('TWO', 'Two'), ('THREE', 'Three'), ('FOUR', 'Four'), ('FIVE', 'Five'), ('SIX', 'Six')], max_length=16)),
                ('start_year', models.IntegerField(default=2018)),
                ('score', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
