# Generated by Django 2.0.1 on 2018-05-18 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_individualscore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individualscore',
            name='contest_index',
        ),
        migrations.RemoveField(
            model_name='individualscore',
            name='league',
        ),
        migrations.RemoveField(
            model_name='individualscore',
            name='start_year',
        ),
    ]
