# Generated by Django 2.0.1 on 2018-05-18 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_auto_20180518_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetedMeet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league', models.CharField(choices=[('GBML', 'Greater Boston Mathematics League'), ('MML', 'Massachusetts Mathematics League'), ('NEAML', 'New England Association of Math Leagues')], max_length=64)),
                ('contest_index', models.CharField(choices=[('ONE', 'One'), ('TWO', 'Two'), ('THREE', 'Three'), ('FOUR', 'Four'), ('FIVE', 'Five'), ('SIX', 'Six')], max_length=16)),
                ('start_year', models.IntegerField(default=2018)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='individualscore',
            name='competed_meet',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.CompetedMeet'),
            preserve_default=False,
        ),
    ]
